name = "transfr-cf"
main = "./src/index.ts"
compatibility_date = "2022-05-03"
workers_dev = true
logpush = true

r2_buckets = [
    { binding = "TEMP_STORE_R2_1", bucket_name = "transfr-temp-bucket-2", preview_bucket_name = "transfr-temp-bucket-2" }
]

[vars]
R2_MAX_FILE_SIZE_BYTES = 21000000 # 20MB
R2_DEFAULT_FILE_TTL = 86400 # 24 hours
R2_DEFAULT_NAMESPACE = "TEMP_STORE_R2_1"
